---
title: "Topic Model"
author: "Erin M. Buchanan"
date: "7/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(topicmodels)
library(rio)
library(tm)
library(slam)
library(ggplot2)
library(tidyverse)
library(tidytext)
library(dplyr)
```

## Data

```{r}
DF <- import("finaldata_LIWC.csv")
```

## Text Cleaning

```{r}
DF$clean <- removeNumbers(DF$Text)
DF$clean <- removePunctuation(DF$clean)
DF$clean <- removeWords(DF$clean, stopwords(kind = "SMART"))
DF$clean <- tolower(DF$clean)
DF$clean <- gsub("[[:punct:]]", " ", DF$clean)
DF$clean <- gsub("\n", " ", DF$clean)
```

## Topic Model

```{r}
import_corpus <- Corpus(VectorSource(DF$clean))
import_matrix <- DocumentTermMatrix(import_corpus)
import_weight <- tapply(import_matrix$v/row_sums(import_matrix)[import_matrix$i], 
                       import_matrix$j, 
                       mean) *
  log2(nDocs(import_matrix)/col_sums(import_matrix > 0))

import_matrix <- import_matrix[ row_sums(import_matrix) > 0, ]

k <- 10 
SEED <- 58934

LDA_fit <- LDA(import_matrix, k = k, 
              control = list(seed = SEED))
```

## Results

```{r}
terms(LDA_fit,20)

LDA_fit_topics <- tidy(LDA_fit, matrix = "beta")
top_terms <- LDA_fit_topics %>%
   group_by(topic) %>%
   top_n(15, beta) %>%
   ungroup() %>%
   arrange(topic, -beta)

top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_bar(stat = "identity", show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  theme_classic() +
  coord_flip()
```

# Interpretating Topics

- Topic 1: Trump Impeachment
- Topic 2: Immigration
- Topic 3: U.S.-China Relations
- Topic 4: Supreme Court
- Topic 5: Party Politics
- Topic 6: Military and Defense
- Topic 7: U.S-Russia Relations
- Topic 8: Technology
- Topic 9: Congress
- Topic 10: Campaign Scandals

```{r}
LDA_gamma <- as.data.frame(tidy(LDA_fit, matrix = "gamma"))
LDA_gamma <- reshape(LDA_gamma, idvar = 'document', timevar = 'topic', direction = 'wide')

DF$document <- row.names(DF)
LDA_topics <- merge(DF, LDA_gamma, by = 'document')
```

```{r}
library(sjPlot)
setwd('C:/Users/kayla/Documents/GitHub/Will-Pilot/manuscript/graphs')
LDA_topics$PartisanLean = as.factor(LDA_topics$PartisanLean)
# 1 = Conservative, 2 = Liberal (neg coeff = )
aff1 = glm(affiliation~gamma.1*PartisanLean, data = LDA_topics)
png('aff1.png')
plot_model(aff1, type='int')
dev.off()
pow1 = glm(power~gamma.1*PartisanLean, data = LDA_topics)
png('pow1.png')
plot_model(pow1, type='int')
dev.off()
ach1 = glm(achieve~gamma.1*PartisanLean, data = LDA_topics)
png('ach1.png')
plot_model(ach1, type='int')
dev.off()

aff2 = glm(affiliation~gamma.2*PartisanLean, data = LDA_topics)
png('aff2.png')
plot_model(aff2, type='int')
dev.off()
pow2 = glm(power~gamma.2*PartisanLean, data = LDA_topics)
png('pow2.png')
plot_model(pow2, type='int')
dev.off()
ach2 = glm(achieve~gamma.2*PartisanLean, data = LDA_topics)
png('ach2.png')
plot_model(ach2, type='int')
dev.off()

aff3 = glm(affiliation~gamma.3*PartisanLean, data = LDA_topics)
png('aff3.png')
plot_model(aff3, type='int')
dev.off()
pow3 = glm(power~gamma.3*PartisanLean, data = LDA_topics)
png('pow3.png')
plot_model(pow3, type='int')
dev.off()
ach3 = glm(achieve~gamma.3*PartisanLean, data = LDA_topics)
png('ach3.png')
plot_model(ach3, type='int')
dev.off()

aff4 = glm(affiliation~gamma.4*PartisanLean, data = LDA_topics)
png('aff4.png')
plot_model(aff4, type='int')
dev.off()
pow4 = glm(power~gamma.4*PartisanLean, data = LDA_topics)
png('pow4.png')
plot_model(pow4, type='int')
dev.off()
ach4 = glm(achieve~gamma.4*PartisanLean, data = LDA_topics)
png('ach4.png')
plot_model(ach4, type='int')
dev.off()

aff5 = glm(affiliation~gamma.5*PartisanLean, data = LDA_topics)
png('aff5.png')
plot_model(aff5, type='int')
dev.off()
pow5 = glm(power~gamma.5*PartisanLean, data = LDA_topics)
png('pow5.png')
plot_model(pow5, type='int')
dev.off()
ach5 = glm(achieve~gamma.5*PartisanLean, data = LDA_topics)
png('ach5.png')
plot_model(ach5, type='int')
dev.off()

aff6 = glm(affiliation~gamma.6*PartisanLean, data = LDA_topics)
png('aff6.png')
plot_model(aff6, type='int')
dev.off()
pow6 = glm(power~gamma.6*PartisanLean, data = LDA_topics)
png('pow6.png')
plot_model(pow6, type='int')
dev.off()
ach6 = glm(achieve~gamma.6*PartisanLean, data = LDA_topics)
png('ach6.png')
plot_model(ach6, type='int')
dev.off()

aff7 = glm(affiliation~gamma.7*PartisanLean, data = LDA_topics)
png('aff7.png')
plot_model(aff7, type='int')
dev.off()
pow7 = glm(power~gamma.7*PartisanLean, data = LDA_topics)
png('pow7.png')
plot_model(pow7, type='int')
dev.off()
ach7 = glm(achieve~gamma.7*PartisanLean, data = LDA_topics)
png('ach7.png')
plot_model(ach7, type='int')
dev.off()

aff8 = glm(affiliation~gamma.8*PartisanLean, data = LDA_topics)
png('aff8.png')
plot_model(aff8, type='int')
dev.off()
pow8 = glm(power~gamma.8*PartisanLean, data = LDA_topics)
png('pow8.png')
plot_model(pow8, type='int')
dev.off()
ach8 = glm(achieve~gamma.8*PartisanLean, data = LDA_topics)
png('ach8.png')
plot_model(ach8, type='int')
dev.off()

aff9 = glm(affiliation~gamma.9*PartisanLean, data = LDA_topics)
png('aff9.png')
plot_model(aff9, type='int')
dev.off()
pow9 = glm(power~gamma.9*PartisanLean, data = LDA_topics)
png('pow9.png')
plot_model(pow9, type='int')
dev.off()
ach9 = glm(achieve~gamma.9*PartisanLean, data = LDA_topics)
png('ach9.png')
plot_model(ach9, type='int')
dev.off()

aff10 = glm(affiliation~gamma.10*PartisanLean, data = LDA_topics)
png('aff10.png')
plot_model(aff10, type='int')
dev.off()
pow10 = glm(power~gamma.10*PartisanLean, data = LDA_topics)
png('pow10.png')
plot_model(pow10, type='int')
dev.off()
ach10 = glm(achieve~gamma.10*PartisanLean, data = LDA_topics)
png('ach10.png')
plot_model(ach10, type='int')
dev.off()
```